-- Table: public.Product
-- DROP TABLE public."Product";

CREATE TABLE IF NOT EXISTS public."Product"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Description" character varying(50) COLLATE pg_catalog."default",
    "Price" numeric(18,2),
    "Cost" numeric(18,2),
    CONSTRAINT "Product_pkey" PRIMARY KEY ("Id")
    )

    TABLESPACE pg_default;

ALTER TABLE public."Product"
    OWNER to postgres;

ALTER TABLE public."Allocation"
    OWNER to postgres;

-- Table: public.Record
-- DROP TABLE public."Record";

CREATE TABLE IF NOT EXISTS public."Record"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ProductId" integer,
    "Quantity" integer,
    "Date" date,
    CONSTRAINT "Record_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "ProductId" FOREIGN KEY ("ProductId")
    REFERENCES public."Product" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    )

    TABLESPACE pg_default;

ALTER TABLE public."Record"
    OWNER to postgres;

-- Table: public.Receipt_Record
-- DROP TABLE public."Receipt_Record";

CREATE TABLE IF NOT EXISTS public."Receipt_Record"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Price" numeric(18,2),
    CONSTRAINT "Receipt_Record_pkey" PRIMARY KEY ("Id")
    )

    TABLESPACE pg_default;

ALTER TABLE public."Receipt_Record"
    OWNER to postgres;

-- Table: public.Received_Record
-- DROP TABLE public."Received_Record";

CREATE TABLE IF NOT EXISTS public."Received_Record"
(
    "Id" integer NOT NULL,
    "Cost" numeric(18,2),
    CONSTRAINT "Received_Record_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "fkey_RecordId" FOREIGN KEY ("Id")
    REFERENCES public."Product" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID
    )

    TABLESPACE pg_default;

ALTER TABLE public."Received_Record"
    OWNER to postgres;

-- Table: public.Allocation
-- DROP TABLE public."Allocation";

CREATE TABLE IF NOT EXISTS public."Allocation"
(
    "ReceiptId" integer NOT NULL,
    "ReceivedId" integer NOT NULL,
    "Allocated_Quantity" integer,
    CONSTRAINT "Allocation_pkey" PRIMARY KEY ("ReceiptId", "ReceivedId"),
    CONSTRAINT "ReceiptId_fkey" FOREIGN KEY ("ReceiptId")
        REFERENCES public."Receipt_Record" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "ReceivedId_fkey" FOREIGN KEY ("ReceivedId")
        REFERENCES public."Received_Record" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;
